brand_name:
  default: 'Financial Peace'
website_url:
  default: 'www.finacialpeace.com'
logo_url:
  default: ''
mobile_logo_url:
  default: ''
links:
  type: list
  default: ''
icons:
  type: list
  default: ''
daily_check_in_url:
  type: string
  default: '/new-topic'
  description: "Enter full url for the Daily Check-in link on Homepage."
daily_check_in_text:
  type: string
  default: 'Ask a Question'
  description: "Enter text for the Daily Check-in button on Homepage."
introduce_yourself:
  type: string
  default: 'Introduce Yourself'
  description: "Enter full url for Introduce Yourself link on Homepage."
